# Generated by Django 3.2.24 on 2025-03-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_player_clan_tag_player_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clan_tag', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='War_player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town_hall_level', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('war_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wars.war')),
            ],
        ),
        migrations.CreateModel(
            name='War_player_attack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('defender_town_hall_level', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('destruction', models.IntegerField()),
                ('opponent_tag', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('attack_time', models.DateTimeField()),
                ('attack_duration', models.IntegerField()),
                ('attack_type', models.CharField(max_length=20)),
                ('war_player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wars.war_player')),
            ],
        ),
    ]
