# Generated by Django 3.2.24 on 2025-03-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='war',
            old_name='clan_tag',
            new_name='opponent_clan_tag',
        ),
        migrations.RemoveField(
            model_name='war_player_attack',
            name='attack_duration',
        ),
        migrations.RemoveField(
            model_name='war_player_attack',
            name='attack_time',
        ),
        migrations.RemoveField(
            model_name='war_player_attack',
            name='attack_type',
        ),
        migrations.AddField(
            model_name='war',
            name='opponent_clan_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
