# Generated by Django 3.2.24 on 2025-03-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0002_auto_20250301_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='war_player',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='war_player',
            old_name='war_id',
            new_name='war',
        ),
        migrations.RenameField(
            model_name='war_player_attack',
            old_name='war_player_id',
            new_name='war_player',
        ),
    ]
