# Generated by Django 3.2.24 on 2025-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0004_war_player_attack_opponent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='state',
            field=models.CharField(default='warEnded', max_length=20),
        ),
    ]
