# Generated by Django 5.1.6 on 2025-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clan_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tag',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
